Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
    - vendor/**/*
  DisplayCopNames: true

Rails:
  Enabled: true

Style/CaseEquality:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false
