Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - bin/*
    - db/schema.rb
    - vendor/**/*
  DisplayCopNames: true

Rails:
  Enabled: true

Style/CaseEquality:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: true

Style/TrailingCommaInArguments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
