base_locale: en
locales:
- en
- ru
data:
  adapter: I18n::Tasks::Data::FileSystem
  router: pattern_router
  read:
  - config/locales/*/%{locale}.yml
  write:
  - [ '{activerecord,admin}.*', 'config/locales/\1/%{locale}.yml' ]
  - config/locales/view/%{locale}.yml
search:
  scanner: I18n::Tasks::Scanners::PatternWithScopeScanner
  relative_roots:
  - app/views
  paths:
  - app/
  - config/navigations/
  exclude:
  - "*.jpg"
  - "*.png"
  - "*.gif"
  - "*.svg"
  - "*.ico"
  - "*.eot"
  - "*.ttf"
  - "*.woff"
  - "*.pdf"
